      subroutine earth(kfildo,ipack,nd5,is3,ns3,l3264b,
     1                 locn,ipos,ier)
c
c        march    2000   lawrence  gsc/tdl   original coding
c        january  2001   glahn     comments; changed ier = 24 to 310
c        january  2001   glahn/lawrence filled some elements of is3( );
c                                  corrected is3(13).eq.2 error to
c                                  is3(15).eq.2; corrected is2(23)
c                                  error to is3(22) in call to pkbg
c        february 2001   glahn/lawrence changed is3(16)=iradius to
c                                  is3(17); and is3(22)=iminaxis to
c                                  is3(27); removed return 1
c
c        purpose
c            packs shape of the earth information into section 3
c            of a grib2 message.  this information is based
c            on table 3.2 of the wmo grib2 documentation and is
c            required by many of the map templates in section 3.
c
c            the user has the option to choose a spherical earth
c            or an oblate spheroid earth. for the spherical earth
c            the user may either use the earth's radius as defined
c            by the wmo or supply his/her own radius value. for the
c            oblate spheroid earth, the user may either use the
c            major and minor axes lengths as defined by the wmo or
c            supply his/her own values for them.
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c              is3(j) = contains the earth-shape information
c                       (in elements 15 through 27) that will be
c                       packed into ipack( ) (j=1,ns3). (input)
c                 ns3 = size of is3( ). (input/output) 
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                locn = the word position to place the next value.
c                       (input/output)
c                ipos = the bit position in locn to start placing
c                       the next value. (input/output)
c                 ier = return status code. (output)
c                         0 = good return.
c                       1-4 = error codes generated by pkbg. see the 
c                             documentation in the pkbg routine.
c                       310 = unsupported shape of earth code in
c                             is3(15).
c
c             local variables
c            earthrad = the earth's radius as outlined in the
c                       wmo grib2 documentation, code table 3.2.
c                       this is in km andapplies to a spherical earth.
c            emajaxis = the major axis of an oblate spheroid earth
c                       as outlined in the wmo grib2 documentation,
c                       code table 3.2.  the value is in km.
c            eminaxis = the minor axis of an oblate spheroid earth
c                       as outlined in the wmo grib2 documentation,
c                       code table 3.2.  the value is in km.
c            imajaxis = the scaled major axis of an oblate spheroid
c                       earth.
c            iminaxis = the scaled minor axis of an oblate spheroid
c                       earth.
c             iradius = the scaled radius of a spherical earth
c            iscalemj = the decimal scale factor to multiply the
c                       major axis of the earth (emajaxis) by to
c                       retain its precision when the value is packed.
c            iscalemn = the decimal scale factor to multiply the
c                       minor axis of the earth (eminaxis) by to
c                       retain its precision when the value is packed.
c            iscalerd = the decimal scale factor to multiply the
c                       radius of the earth (earthrad) by to
c                       retain its precision when the value is packed.
c                   n = l3264b = the integer word length in bits of
c                       the machine being used. values of 32 and
c                       64 are accommodated.
c
c        non system subroutines called
c           pkbg
c
      parameter (earthrad=6367.47,
     1           iscalerd=2,
     2           emajaxis=6378.160,
     3           iscalemj=3,
     4           eminaxis=6356.775,
     5           iscalemn=3)
c
      dimension ipack(nd5),is3(ns3)
c
      data izero/0/
c
      n=l3264b
      ier=0
c
c        pack the shape of the earth.
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(15),8,n,ier,*900)
c
c        depending on the shape of the earth that the
c        user has chosen, pack the appropriate scale
c        factor and value for the radius of the earth.
      if((is3(15).eq.0).or.(is3(15).eq.1))then
c
         if(is3(15).eq.0)then
c              pack the scale factor of the radius of the
c              spherical earth and the scaled radius of the
c              spherical earth as defined in the wmo grib2
c              documentation, in this case 2.
            iradius=nint((10**iscalerd)*earthrad)
            call pkbg(kfildo,ipack,nd5,locn,ipos,iscalerd,8,n,
     1                ier,*900)
            is3(16)=iscalerd
            call pkbg(kfildo,ipack,nd5,locn,ipos,iradius,
     1                32,n,ier,*900)
            is3(17)=iradius
         else
c
c              pack the scale factor of the radius of the
c              spherical earth and the scaled radius of the
c              spherical earth as defined by the user in the
c              is3( ) array.
            call pkbg(kfildo,ipack,nd5,locn,ipos,is3(16),8,n,
     1                ier,*900)
            call pkbg(kfildo,ipack,nd5,locn,ipos,is3(17),32,n,
     1                ier,*900)
         endif
c
c           zero out the locations pertaining to an oblate
c           spheriod earth.
c
         call pkbg(kfildo,ipack,nd5,locn,ipos,izero,32,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,izero,32,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,izero,16,n,ier,*900)
c
      elseif((is3(15).eq.2).or.(is3(15).eq.3))then
c
c           zero out the locations pertaining to a spherical
c           earth.
c
         call pkbg(kfildo,ipack,nd5,locn,ipos,izero,32,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,izero,8,n,ier,*900)
c
         if(is3(15).eq.2)then
c
c              pack the scale factor of the major and minor
c              axes of an oblate spheroid earth along with
c              with their scaled values as defined by the
c              wmo grib2 documentation.
            imajaxis=nint((10**iscalemj)*emajaxis)
            call pkbg(kfildo,ipack,nd5,locn,ipos,iscalemj,8,n,
     1                ier,*900)
            is3(21)=iscalemj
            call pkbg(kfildo,ipack,nd5,locn,ipos,imajaxis,
     1                32,n,ier,*900)
            is3(22)=imajaxis
            iminaxis=nint((10**iscalemn)*eminaxis)
            call pkbg(kfildo,ipack,nd5,locn,ipos,iscalemn,8,n,
     1                ier,*900)
            is3(26)=iscalemn
            call pkbg(kfildo,ipack,nd5,locn,ipos,iminaxis,
     1                32,n,ier,*900)
            is3(27)=iminaxis
         else
c
c              pack the scale factor of the major and minor
c              axes of an oblate spheroid earth along with
c              with their scaled values as defined by the
c              user.
            call pkbg(kfildo,ipack,nd5,locn,ipos,is3(21),8,n,
     1                ier,*900)
            call pkbg(kfildo,ipack,nd5,locn,ipos,is3(22),
     1                32,n,ier,*900)
            call pkbg(kfildo,ipack,nd5,locn,ipos,is3(26),8,n,
     1                ier,*900)
            call pkbg(kfildo,ipack,nd5,locn,ipos,is3(27),
     1                32,n,ier,*900)
         endif
c
      else
c           an invalid or unsupported code for the shape of the
c           earth is in is3(15).
         ier=310
      endif
c
 900  return
      end
