      subroutine pk_orthographic(kfildo,ipack,nd5,is3,ns3,ipkopt,
     1                           l3264b,locn,ipos,ier,*)
c
c        march   2000   lawrence   gsc/tdl   original coding
c        january 2001   glahn      comments; ier = 303 changed to 304;
c                                  added check for size of is3( )
c        january 2001   glahn/lawrence changed is3(65) to abs(is3(65))
c                                  in call to bkbg
c
c        purpose
c            packs template 3.90, a space view perspective
c            (orthographic) map projection template in section 3.
c            it is the responsibility of the calling routine to
c            pack the first 13 octets in section 3.
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c              is3(j) = contains the mercator projection
c                       information (in elements 15 through 77)
c                       that will be packed into ipack( ) (j=1,ns3).
c                       (input/output)
c                 ns3 = size of is3( ). (input) 
c              ipkopt = packing indicator:
c                       0 = error, don't pack
c                       1 = pack ia( ), simple
c                       2 = pack ia( ) and ib( ), simple
c                       3 = pack complex or spatial differencing
c                       4 = pack complex.
c                       (input)
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                locn = the word position to place the next value.
c                       (input/output)
c                ipos = the bit position in locn to start placing
c                       the next value. (input/output)
c                 ier = return status code. (output)
c                         0 = good return.
c                       1-4 = error codes generated by pkbg. see the 
c                             documentation in the pkbg routine.
c                       302 = is3( ) has not been dimensioned large
c                             enough to contain the entire template. 
c                       304 = is3(13) does not indicate polar
c                             stereographic map projection; 
c                             incorrectly called subroutine. 
c                       310 = unrecognized or unsupported shape of
c                             earth code in is3(15) returned by
c                             subroutine earth.
c                   * = alternate return when ier .ne. 0
c
c             local variables
c               isign = a flag indicating whether a value to be
c                       packed is positive or negative.
c                   n = l3264b = the integer word length in bits of
c                       the machine being used. values of 32 and
c                       64 are accommodated.
c             minsize = the smallest allowable dimension for is3( ).
c
c        non system subroutines called
c           earth, pkbg
c
      parameter(minsize=77)
c
      dimension ipack(nd5),is3(ns3)
c
      n=l3264b
      ier=0
c
c        check to make sure that the user wants to process
c        a space view perspective projection.  check for ns3 ge 13
c        assures a value for is3(13).
c
      if(ns3.ge.13)then
c
         if (is3(13).ne.90)then
c           write(kfildo,10)is3(13)
c10         format(/' map projection code ',i4,' indicated by is3(13)'/
c    1              ' is not space view perspective. please refer to'/
c    2              ' the grib2 documentation to determine the'/
c    3              ' correct map projection packer to call.'/) 
            ier=304
            go to 900
         endif
c
      else
         ier=302
         go to 900
      endif
c
c        check the dimensions of is3( ).
c
      if(ns3.lt.minsize)then
         ier=302
         go to 900
      endif
c
c        pack the shape of the earth.
      call earth(kfildo,ipack,nd5,is3,ns3,n,locn,ipos,ier)
      if(ier.ne.0)goto 900
c
c        pack the number points along the x-axis and the number
c        of points along the y-axis (nx & ny).
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(31),32,n,ier,*900)
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(35),32,n,ier,*900)
c
c        pack the latitude & longitude of the sub-satellite point 
c        taking into consideration that the value may be
c        negative.
      isign=0
      if(is3(39).lt.0) isign=1
      call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
      call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is3(39)),
     1          31,n,ier,*900)
      isign=0
      if(is3(43).lt.0) isign=1
      call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
      call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is3(43)),
     1          31,n,ier,*900)
c
c        pack the resolution and component flags.
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(47),8,n,ier,*900)
c
c        pack the apparent diameter of the earth in grid lengths,
c        in the x-direction and the y-direction.
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(48),32,n,ier,*900)
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(52),32,n,ier,*900)
c
c        pack the x-coordinate of the sub-satellite point. 
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(56),32,n,ier,*900)
c
c        pack the y-coordinate of the sub-satellite point. 
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(60),32,n,ier,*900)
c
c        pack the scanning mode. check to see if the data points 
c        have been ordered boustrophedonically. if so, set bit 4
c        to 1 in the scanning mode octet.
c
cwdt  if((ipkopt.eq.3).or.(ipkopt.eq.4))then
cwdt     is3(64)=ior(is3(64),16)
cwdt  else
         is3(64)=iand(is3(64),239)
cwdt  endif
c
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(64),8,n,ier,*900)
c
c        pack the orientation angle of the grid (the angle
c        between the map's i direction and the earth's
c        equator). allow for this value to be negative.
      isign=0
      if(is3(65).lt.0) isign=1
      call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
      call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is3(65)),31,n,ier,*900)
c
c
c        pack the altitude of the camera from the earth's center
c        measured in units of the earth's equatorial radius.
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(69),32,n,ier,*900)
c
c        pack the x-coordinate of the sector image (xo)
c        and the y-coordinate of the sector image (yo).
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(73),32,n,ier,*900)
      call pkbg(kfildo,ipack,nd5,locn,ipos,is3(77),32,n,ier,*900)
c
c       error return section
 900  if(ier.ne.0)return 1 
c
      return
      end
