      subroutine pk_sect8(kfildo,ipack,nd5,locn,ipos,l3264b,ier,
     1                    isevere,*)
c
c        april   2000   glahn   tdl   for grib2
c        january 2001   glahn   comments; standardized return
c
c        purpose
c            packs section 8, the end section, of a grib2 message.
c            it consists of '7777'.
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c                locn = indicates the word position to put '7777'.
c                       (input/output)
c                ipos = indicates the bit position in locn to put
c                       '7777'.  (input/output)
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                 ier = return status code. (output)
c                         0 = good return.
c                       1-4 = errors generated by the pkbg routine. see
c                             the documentation for the pkbg routine.
c             isevere = the severity level of the error.  the only
c                       value retuned is:
c                       2 = a fatal error  (output)
c                   * = alternate return when ier ne 0.
c
c             local variables
c               c7777 = ascii 7777.
c               i7777 = equivalenced to c7777.
c              i7777s = i7777 in right half of word.  this is
c                       necessary when l3264b = 64.
c
c        non system subroutines called
c           pkbg
c
      character*4 c7777
c
      dimension ipack(nd5)
c
      equivalence (c7777,i7777)
c
      data c7777/'7777'/
c
      i7777s=i7777
c
c        all errors generated by this routine are fatal.
      isevere=2
c
      if(l3264b.eq.64)i7777s=ishft(i7777,-32)
c        the above statement moves the ascii 7777 to the right
c        half of the work when l3264b = 64.  pkbg will not
c        overflow ipack( ).
      call pkbg(kfildo,ipack,nd5,locn,ipos,i7777s,32,l3264b,
     1          ier,*900)
c
c        error return section
 900  if(ier.ne.0)return 1
c
      return
      end
