      subroutine pk_sect4(kfildo,ipack,nd5,is4,ns4,l3264b,
     1                    locn,ipos,ier,isevere,*)
c
c        march    2000   lawrence  gsc/tdl   original coding
c        january  2001   glahn     comments; eliminated duplicate
c                                  loc4 and ipos4 initialization;
c                                  added test for size of is4( )
c        february 2001   glahn/lawrence added template names
c        july     2002   rudack    added addtional case statement to
c                                  accommodate template 4.9.
c
c        purpose
c            packs section 4, the product definition section,
c            of a grib2 message.
c
c            this routine is capable of packing the following
c            product definition templates:
c               template 4.0  analysis or forecast at a level and point
c               template 4.1  individual emsemble
c               template 4.2  derived forecast based on ensembles
c               template 4.8  average, accumulation, extremes
c               template 4.9  probability forecasts at a horizontal level
c               template 4.20 radar
c               template 4.30 satellite
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c              is4(j) = contains the grid definition data that
c                       will be packed into ipack( ) (j=1,ns4).
c                       (input)
c                 ns4 = size of is4( ). (input/output)
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                locn = the word position to place the next value.
c                       (input/output)
c                ipos = the bit position in locn to start placing
c                       the next value. (input/output)
c                 ier = return status code. (output)
c                         0 = good return.
c                        1-4 = error codes generated by pkbg. see the 
c                              documentation in the pkbg routine.
c                        5,6 = error code generated by the length
c                              function. see the documentation for the
c                              length function.
c                        401 = is4(5) does not indicate section 4.
c                        402 = is4( ) has not been dimension large enough
c                              to contain the entire template indicated
c                              by the code in is4(6).  returned by
c                              routines like pk_temp40.
c                        403 = is4(8) does not contain a supported 
c                              template number.
c             isevere = the severity level of the error.  the only
c                       value retuned is:
c                       2 = a fatal error  (output)
c                   * = alternate return when ier ne 0.
c
c             local variables
c                loc4 = saves the word position in ipack
c                       to store the length of section 4
c                       after the routine is done packing 
c                       data into the section.
c               ipos4 = saves the bit position in loc4
c                       to store the length of section 4
c                       after the routine is done packing
c                       data into the section.
c               izero = contains the value '0'.  this is used in the
c                       code simply to emphasize that a certain 
c                       group of octets in the message are being 
c                       zeroed out.
c                   k = a looping index variable.
c                   n = l3264b = the integer word length in bits of
c                       the machine being used. values of 32 and
c                       64 are accommodated.
c
c        non system subroutines called
c           length, pk_temp40, pk_temp41, pk_temp42, pk_temp48, pk_temp420,
c           pk_temp430, pk_temp49, pkbg
c
      parameter(minsize=8)
c
      dimension ipack(nd5),is4(ns4)
c
      data izero/0/
c
      n=l3264b
      ier=0
c
      loc4=locn
      ipos4=ipos
c
c        all errors generated by this routine are fatal.
c
      isevere=2
c
c        check minimum size of is4( ).  template sizes checked
c        in template subroutines.
c
      if(ns4.lt.minsize)then
         ier=402
         go to 900
      endif
c
c        check to make sure that data has been provided for 
c        section 4.  there must always be a section 4.
c
      if(is4(5).ne.4)then
         ier=401
      else
c           bytes 1-4 must be filled in later with the record length
c           in bytes; below statement holds the place.  loc4 and ipos4
c           hold the location.
         call pkbg(kfildo,ipack,nd5,locn,ipos,izero,32,n,ier,*900)
c
c           pack the section number, in this case 4.
         call pkbg(kfildo,ipack,nd5,locn,ipos,4,8,n,ier,*900)
c
c           pack the number of coordinates values after template.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(6),16,n,ier,*900)
c
c           pack the product definition template.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(8),16,n,ier,*900)
c
c           pack the data representation template.
         select case (is4(8))
c
            case (0)
c
c                 analysis or forecast at a horizontal level or in a
c                 horizontal layer at a point in time.
               call pk_temp40(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                        ipos,ier,*900)
c
            case (1)
c
c                 individual ensemble forecast, control and perturbed,
c                 at a horizontal level or in a horizontal layer at a
c                 point in time.
               call pk_temp41(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                        ipos,ier,*900)
c
            case(2)
c
c                 derived forecast based on all ensemble members at
c                 a horizontal level or in a horizontal layer at a
c                 point in time.
               call pk_temp42(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                        ipos,ier,*900)
c
            case(8)
c
c                 average, accumulation, and/or extreme values at a
c                 horizontal level or in a horizontal layer in a
c                 continuous or non-continuous time interval
               call pk_temp48(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                        ipos,ier,*900)
c
            case(9)
c
c               a probability forecast at a horizontal level
c               or in a horizontal layer in a continuous or
c               non-continuous time interval. (template 4.9)
c               (pop12)
               call pk_temp49(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                        ipos,ier,*900)
c
            case(20)
c
c                 a radar product.
               call pk_temp420(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                         ipos,ier,*900)
c
            case(30)
c
c                 a satellite product.
               call pk_temp430(kfildo,ipack,nd5,is4,ns4,n,locn,
     1                         ipos,ier,*900)
c
            case default
c
c                 the product template is unrecognized
               ier=403
               go to 900
         end select      
c   
c           compute the length of the section and pack it.
         is4(1)=length(kfildo,ipack,nd5,l3264b,loc4,ipos4,locn,
     1                 ipos,ier)
c
      endif
c
c        error return section
 900  if(ier.ne.0)return 1 
c
      return
      end
