      subroutine pk_temp430(kfildo,ipack,nd5,is4,ns4,l3264b,
     1                      locn,ipos,ier,*)
c
c        march   2000   lawrence   gsc/tdl   original coding
c        january 2001   glahn      comments; ier = 941 changed to 403;
c                                  changed algorithm for checking is4( )
c                                  size; ier = 403 changed to 402
c        january 2001   glahn/lawrence corrected error is4(42) to
c                                  is4(14) when checking for is4( ) size
c
c        purpose
c            packs template 4.30 into product definition section 
c            of a grib2 message.  template 4.30 is for a satellite
c            product. it is the responsibility of the calling routine
c            to pack the first 9 octets in section 4.
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c              is4(j) = contains the product definition information
c                       for template 4.30 (in elements 10 through
c                       14 or more, depending on the number of bands,
c                       to be packed into ipack( ) (j=1,ns4). (input)
c                 ns4 = size of is4( ). (input)
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                locn = the word position to place the next value.
c                       (input/output)
c                ipos = the bit position in locn to start placing
c                       the next value. (input/output)
c                 ier = return status code. (output)
c                        0 = good return.
c                       1-4 = error codes generated by pkbg. see the 
c                             documentation in the pkbg routine.
c                       402 = is4( ) has not been dimensioned large
c                             enough to contain the entire template.
c                   * = alternate return when ier ne 0.
c
c             local variables
c               isize = the smallest allowable dimension for is4( )
c                       when the data for all of the contributing
c                       bands has been accounted for.
c             minsize = the smallest allowable dimension for is4( ).
c                   l = a loop indexing variable.
c                   m = an array indexing variable.
c                   n = l3264b = the integer word length in bits of
c                       the machine being used. values of 32 and
c                       64 are accommodated.
c
c        non system subroutines called
c           pkbg
c
      parameter(minsize=14)
c
      dimension ipack(nd5), is4(ns4)
c
      n=l3264b
      ier=0
c
c        check the dimensions of is4( ).
c
      if(ns4.lt.minsize)then
c        write(kfildo,10)ns4,minsize
c10      format(/' is4( ) is currently dimensioned to contain'/
c    1           ' ns4=',i4,' elements. this array must be'/
c    2           ' dimensioned to at least ',i4,' elements'/
c    3           ' to contain all of the data in product'/
c    4           ' definition template 4.30.'/)
         ier=402
      else
c
c           pack the parameter category.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(10),8,n,ier,*900)
c
c           pack the parameter number.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(11),8,n,ier,*900)
c
c           pack the type of generating process. 
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(12),8,n,ier,*900)
c
c           pack the observation generating process identifier.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(13),8,n,ier,*900)
c
c           pack the number of contributing bands.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(14),8,n,ier,*900)
c
c           check to make sure that is4( ) was dimensioned
c           large enough to contain the data for all of the
c           contributing bands.
c
         if(ns4.lt.minsize+10*(is4(14))-3)then
            ier=402
c
c           write(kfildo,20)ns4,isize
c20         format(/' is4( ) is currently dimensioned to contain'/
c    1              ' ns4=',i4,' elements. this array must be'/
c    2              ' dimensioned to at least ',i4,' elements'/
c    3              ' to contain all of the contributing band data'/
c    4              ' in product definition template 4.30.'/)
         else
c
c              for each of the contributing bands
c              (indicated in is4(14)) pack 5 values.
c
            do l=1,is4(14)
               m = 15 + 10*(l-1)
               call pkbg(kfildo,ipack,nd5,locn,ipos,is4(m),16,n,
     1                   ier,*900)
               call pkbg(kfildo,ipack,nd5,locn,ipos,is4(m+2),16,n,
     1                   ier,*900)
               call pkbg(kfildo,ipack,nd5,locn,ipos,is4(m+4),8,n,
     1                   ier,*900)
               call pkbg(kfildo,ipack,nd5,locn,ipos,is4(m+5),8,n,
     1                   ier,*900)
               call pkbg(kfildo,ipack,nd5,locn,ipos,is4(m+6),32,n,
     1                   ier,*900)
            enddo
c
         endif
c
      endif
c
c       error return section
 900  if(ier.ne.0)return 1
c
      return
      end
