      subroutine pk_temp40(kfildo,ipack,nd5,is4,ns4,l3264b,
     1                     locn,ipos,ier,*)
c
c        march   2000   lawrence   gsc/tdl   original coding
c        january 2001   glahn      comments; ier=403 changed to 402
c
c        purpose
c            packs template 4.0 into product definition section 
c            of a grib2 message.  template 4.0 is for an analysis
c            or forecast at a horizontal level or in a horizontal
c            layer at a point in time.  it is the responsibility
c            of the calling routine to pack the first 9 octets
c            in section 4.
c
c            note that template 4.0 forms the basis for many
c            of the other product definition templates 
c            available to be packed in section 4 of the grib2
c            message.
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c              is4(j) = contains the product definition information 
c                       for template 4.0 (in elements 10 through 31)
c                       that will be packed into ipack( ) (j=1,ns4).
c                       (input)
c                 ns4 = size of is4( ). (input) 
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                locn = the word position to place the next value.
c                       (input/output)
c                ipos = the bit position in locn to start placing
c                       the next value. (input/output)
c                 ier = return status code. (output)
c                        0 = good return.
c                       1-4 = error codes generated by pkbg. see the 
c                             documentation in the pkbg routine.
c                       402 = is4( ) has not been dimensioned large
c                             enough to contain the entire template. 
c                   * = alternate return when ier ne 0. 
c
c             local variables
c             minsize = the smallest allowable dimension for is4( ).
c                   n = l3264b = the integer word length in bits of
c                       the machine being used. values of 32 and
c                       64 are accommodated.
c
c        non system subroutines called
c           pkbg
c
      parameter(minsize=31)
c
      dimension ipack(nd5),is4(ns4)
c
      n=l3264b
      ier=0
c
c        check the dimensions of is4( ).
c
      if(ns4.lt.minsize)then
         ier=402
      else
c
c           pack the product definition template.
c        
c           pack the parameter category.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(10),8,n,ier,*900)
c
c           pack the parameter number.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(11),8,n,ier,*900)
c
c           pack the type of generating process.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(12),8,n,ier,*900)
c
c           pack the background generating process identifier.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(13),8,n,ier,*900)
c
c           pack the analysis or forecast generating process identifier.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(14),8,n,ier,*900)
c
c           pack the hours of observational data cutoff after 
c           reference time.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(15),16,n,ier,*900)
c
c           pack the minutes of observational data cutoff after
c           reference time.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(17),8,n,ier,*900)
c
c           pack the indicator of unit of time range.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(18),8,n,ier,*900)
c
c           pack the forecast time in units defined by octet 19.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(19),32,n,ier,*900)
c
c           pack the type of first fixed surface.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(23),8,n,ier,*900)
c
c           pack the scale factor of first fixed surface.
         isign=0
         if(is4(24).lt.0) isign=1
         call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is4(24)),7,n,ier,*900)
c
c           pack the scaled value of first fixed surface.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(25),32,n,ier,*900)
c
c           pack the type of second fixed surface.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(29),8,n,ier,*900)
c
c           pack the scale factor of second fixed surface.
         isign=0
         if(is4(30).lt.0) isign=1
         call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is4(30)),7,n,ier,*900)
c
c           pack the scaled value of second fixed surface.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(31),32,n,ier,*900)
      endif
c
c       error return section
 900  if(ier.ne.0)return 1 
c
      return
      end
