      subroutine pk_temp420(kfildo,ipack,nd5,is4,ns4,l3264b,
     1                      locn,ipos,ier,*)
c
c        march   2000   lawrence   gsc/tdl   original coding
c        january 2001   glahn      comments; ier = 403 changed to 402
c
c        purpose
c            packs template 4.20 into product definition section 
c            of a grib2 message.  template 4.20 is for a radar product.
c            it is the responsibility of the calling routine to pack
c            the first 9 octets in section 4.
c
c        data set use
c           kfildo - unit number for output (print) file. (output)
c
c        variables
c              kfildo = unit number for output (print) file. (input)
c            ipack(j) = the array that holds the actual packed message
c                       (j=1,nd5). (input/output)
c                 nd5 = the size of the array ipack( ). (input)
c              is4(j) = contains the product definition information
c                       for template 4.20 (in elements 10 through 42)
c                       to be packed into ipack( ) (j=1,ns4). (input)
c                 ns4 = size of is4( ). (input)
c              l3264b = the integer word length in bits of the machine
c                       being used. values of 32 and 64 are
c                       accommodated. (input)
c                locn = the word position to place the next value.
c                       (input/output)
c                ipos = the bit position in locn to start placing
c                       the next value. (input/output)
c                 ier = return status code. (output)
c                         0 = good return.
c                       1-4 = error codes generated by pkbg. see the 
c                             documentation in the pkbg routine.
c                       402 = is4( ) has not been dimensioned large
c                             enough to contain the entire template.
c                   * = alternate return when ier ne 0.
c
c             local variables
c             minsize = the smallest allowable dimension for is4( ).
c                   n = l3264b = the integer word length in bits of
c                       the machine being used. values of 32 and
c                       64 are accommodated.
c
c        non system subroutines called
c           pkbg
c
      parameter(minsize=42)
c
      dimension ipack(nd5),is4(ns4)
c
      n=l3264b
      ier=0
c
c        check the dimensions of is4( ).
c
      if(ns4.lt.minsize)then
c        write(kfildo,10)ns4,minsize
c10      format(/' is4( ) is currently dimensioned to contain'/
c    1           ' ns4=',i4,' elements. this array must be'/
c    2           ' dimensioned to at least ',i4,' elements'/
c    3           ' to contain all of the data in product'/
c    4           ' definition template 4.20.'/)
         ier=402
      else
c
c           pack the parameter category.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(10),8,n,ier,*900)
c
c           pack the parameter number.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(11),8,n,ier,*900)
c
c           pack the type of generating process.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(12),8,n,ier,*900)
c
c           pack the number of radar sites used.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(13),8,n,ier,*900)
c
c           pack the indicator of unit of time range.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(14),8,n,ier,*900)
c
c           pack the latitude & longitude of the site.
         isign=0
         if(is4(15).lt.0) isign=1
         call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is4(15)),
     1             31,n,ier,*900)
         isign=0
         if(is4(19).lt.0) isign=1
         call pkbg(kfildo,ipack,nd5,locn,ipos,isign,1,n,ier,*900)
         call pkbg(kfildo,ipack,nd5,locn,ipos,abs(is4(19)),
     1             31,n,ier,*900)
c
c           pack the site elevation.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(23),16,n,ier,*900)
c 
c           pack the alphanumeric site identifier.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(25),32,n,ier,*900)
c
c           pack the numeric site identifier. 
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(29),16,n,ier,*900)
c
c           pack the operating mode, reflectivity calibration
c           constant, quality control indicator, clutter filter
c           indicator, and constant antenna elevation angle.
c
         do k=31,35
            call pkbg(kfildo,ipack,nd5,locn,ipos,is4(k),8,n,ier,*900)
         end do
c
c           pack the accumulation interval.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(36),16,n,ier,*900)
c
c           pack the reference reflectivity for echo top.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(38),8,n,ier,*900)
c
c           pack the range bin spacing.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(39),24,n,ier,*900)
c
c           pack the radial angular spacing.
         call pkbg(kfildo,ipack,nd5,locn,ipos,is4(42),16,n,ier,*900)
c
      endif
c
c       error return section
 900  if(ier.ne.0)return 1 
c
      return
      end
